### ISSUE TITLE
dar feedback a manual push

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/qa-control-server#11]
que vaya mostrando los comandos

**Comment by diegoefe** [comment]
Para hacerlo andar tuve que hacer esto:

  res.setHeader('Connection', 'Transfer-Encoding');
  **res.setHeader('Content-Type', 'text/html; charset=utf-8');**
  res.setHeader('Transfer-Encoding', 'chunked');

Si uso text/plain los browsers bufferean.
Para manual-push no hay problema pero sabés cómo lograrlo con text/plain?
