### ISSUE TITLE
No permitir agregar un repositorio que no existe en github

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/qa-control-server#18]
para saber qué repositorios existen se puede usar el api de github haciendo un

```
GET https://api.github.com/orgs/codenautas/repos
```

(donde codenautas puede ser cualquier organización).

**Comment by diegoefe** [comment]
Esto corre también para las organizaciones supongo... es así?
(que no puedan agregar una organización inexistente en github)

**Comment by emilioplatzer** [comment]
Sí, vale

**Comment by diegoefe** [comment]
ok
