### ISSUE TITLE
Agregar (si existe) la opción que no muestre porcentajes de avance en git clone

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/qa-control-server#19]
Actualmente, cuando el clone demora muestra el avance en forma de porcentaje.

Por ejemplo en el URL: `http://localhost:7226/manual-push/codenautas/qa-control`. La salida es:

``` sh
Pushing manually...
git clone https://github.com/codenautas/qa-control.git local-info\groups\codenautas\projects\qa-control\source
Cloning into 'local-info\groups\codenautas\projects\qa-control\source'... 
Checking out files: 12% (9/74) 
Checking out files: 13% (10/74) 
Checking out files: 14% (11/74) 
...
```

**Comment by diegoefe** [comment]
Según https://git-scm.com/docs/git-clone, la opcion -q hace exactamente eso.
En mi versión de git (1.9.5.msysgit.1) no obtengo una salida como la tuya (nunca mestra progreso).
La opción está agregada y no veo diferencia sustancial en mi versión, cerrá el issue si se resolvió en la tuya.

**Comment by emilioplatzer** [comment]
Listo para mí. Si falla lo reabro
