### ISSUE TITLE
Si scoring es obligatorio debe garantizarse en qa-control

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/qa-control-server#23]
Y si no se genere debe mostrarse N/A
- Además: Mejorar el despliegue del scoring (solo se mostraba el custom).

**Comment by diegoefe** [comment]
No entiendo esto.
qa-control-server no activa scoring cuando llama a controlProject().
Quién debe activarlo?

**Comment by emilioplatzer** [comment]
Como está programado ahora puede ocurrir que los warnings de qa-control se emitan sin el campo scoring. Antes de mi intervención para mostrar scoring el programa de qa-control-server buscaba w.scoring.custom (por lo tanto si scoring no existía el programa abortaba). Eso es lo que está mal, que esté programado para que sí o sí haya algo que no se garantizaba que esté. 

Ahora muestra el json de scoring (si está), debería mostrar algo más bonito que un JSON.

**Comment by emilioplatzer** [comment]
Creo que no encontramos la manera de garantizar los warnings, en esta caso el scoring (de la misma manera que no hay cómo garantizar que el mensaje esté traducido). Recordemos no esperar que siempre exista.
