### ISSUE TITLE
Que al servir en una cucarda que no está en el repositorio ponga N/A

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/qa-control-server#25]
Que si no existe el repositorio sirva una cucarda gris (igual que las otras invalid que solemos ver como la de coverage de js-from-html) cuyo texto sea N/A

**Comment by diegoefe** [comment]
Si te referís a la página de la organización (p.e. http://localhost:7226/codenautas), decís que esta cucarda debe aparecer en todos los lugares donde va una pero no existe para el proyecto?
p.e. kill-9 tendría una en cada columna menos en la de "issues" y "qa-control"

**Comment by emilioplatzer** [comment]
Al contrario. Digo que por ejemplo en:

``` url
https://github.com/emilioplatzer/pizarra
```

hacer referencia a:

``` url
http://codenautas.com/github/emilioplatzer/pizarra.svg
```

y si bien emilioplatzer existe en `http://codenautas.com/github/emilioplatzer/` lo que no existe es el proyecto `pizarra`. En estos casos creo que sería conveniente servir una cucarda que en vez de `qa-control: n err` diga `qa-control: N/A`

**Comment by diegoefe** [comment]
Pero es para casos en los que existía y fue removido nada más?

**Comment by emilioplatzer** [comment]
Para casos donde el repositorio es nuevo, todavía no se registró en codenautas.com pero uno quiere que pase los controles de cucardas de qa-control localmente

**Comment by diegoefe** [comment]
Si no entendí mal, en este momento http://codenautas.com/github/emilioplatzer/pizarra, responde "404 Internal error", no "qa-control: n err.", es así o estoy confundiéndome de link?

**Comment by emilioplatzer** [comment]
Lo voy a subir cuando
- [ ]  haya revisado el #26
- [ ]  esté terminado el #27
