### ISSUE TITLE
Poner en brightgreen el "ok" cuando se esté controlando con la última versión disponible

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/qa-control-server#26]
El punto donde creo que hay que poner el control es donde actualmente dice

``` js
if("last version"){
```

(que justamente lo puse para marcar el lugar porque creo que es ahí.

**Comment by emilioplatzer** [comment]
Nunca comparar con un ID (ej: `warn.warning==='older_version_of_qa_control_in_package_json'`), hay que comparar una característica (ej: notice). 

O sea cuando es gravity notice en vez de mostrar la cantidad de notices se pone ok en verde. 

Es más tampoco debería controlarse gravity notice sino por una característica de gravity. Por ejemplo:

``` js
        var count={
            error  :{count:0, abr:'err', color:'red'   },
            obs    :{count:0, abr:'obs', color:'yellow'},
            warning:{count:0, abr:'war', color:'orange'},
            notice :{count:0, abr:'not', color:'ffdb99'}, // naranja claro
        }
```

podría llamarse gravities (en vez de count) y en el caso de notice poner: equalOk. Algo así como

``` js
        var gravities = {
            error  :{abr:'err', color:'red'   },
            obs    :{abr:'obs', color:'yellow'},
            warning:{abr:'war', color:'orange'},
            notice :{abr:'not', color:'green', equalOk:true}, 
        }
```

y usar gravities para saber la abreviación, el color, o si debe reemplazarse por ok. O mejor:

``` js
        var gravities = {
            error  :{label:'% err', color:'red'   },
            obs    :{label:'% obs', color:'yellow'},
            warning:{label:'% war', color:'orange'},
            notice :{label:'ok', color:'green'}, 
        }
```

En ese caso para todos es lo mismo, se pone el label reemplazando "%" por la cantidad (y notice no tiene % así que el reemplazo no hace nada).

**Comment by diegoefe** [comment]
Y cuándo haya más notice's y me interese sólo el que ser refiere a la versión vieja?

**Comment by emilioplatzer** [comment]
No se llamarán notices, serán observaciones

**Comment by diegoefe** [comment]
Como sea, si los scoring: {notice:1}  son observaciones, van a salir en la cucarda final, no se va a ver el "ok" que vos querés, hay que remover el warning correspondiente para que eso pase...

**Comment by emilioplatzer** [comment]
Acabo de instalarlo. Se ve bien.

**Comment by diegoefe** [comment]
Cerramos este issue?
