### ISSUE TITLE
No encuentra self-explain

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/qa-control-server#30]
Al intentar agregar self-explain me sale 

```
inexistent project on github 
```

En el log pone:

```
doRepoUpdate err Error: inexistent project on github
    at /home/nuestros/programas/qa-control-server/lib/qac-services.js:566:19
    at tryCallOne (/home/nuestros/programas/qa-control-server/node_modules/best-promise/node_modules/promise/lib/core.js:37:12)
    at /home/nuestros/programas/qa-control-server/node_modules/best-promise/node_modules/promise/lib/core.js:103:15
    at flush (/home/nuestros/programas/qa-control-server/node_modules/best-promise/node_modules/promise/node_modules/asap/raw.js:50:29)
    at process._tickCallback (node.js:355:11)
```

**Comment by emilioplatzer** [comment]
pasa lo mismo con `require-bro`, quizás sea por el guiòn.

**Comment by emilioplatzer** [comment]
Pruebo con otro: `project "regexplicit" created`

**Comment by diegoefe** [comment]
El problema no está en el proyecto, casi seguro que tiene que ver con las nuevas políticas de seguridad de github, fijate que en mini-tools, p.e., hay un team que debe ser producto del upgrade:
![pro_team](https://cloud.githubusercontent.com/assets/1447920/15291485/8c841f3c-1b54-11e6-8598-7a779ab809e8.png)
En cambio acá falta el team:
![pro_no_team](https://cloud.githubusercontent.com/assets/1447920/15291492/915200ec-1b54-11e6-8425-1a1c2a617e69.png)

**Comment by emilioplatzer** [comment]
Entiendo que ya está
