### ISSUE TITLE
mostrar la bitácora y los resultados con los detalles

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/qa-control-server#5]
Luego de las cucardas agregar un DIV que tenga una línea por cada bitácora. 
- esa línea es un elemento de tipo PRE
- la clase es el origin
- el timestamp va como title

Linkear la página con un .css igual a `.....\npm\exec-to-html\bin\exec-control.css` con el agregado de la clase internal. 

Luego en otro DIV en letra 2 puntos más grandes mostrar los resultados que están en `qa-control-result.json`, también línea por línea (pero estas líneas son DIV)

**Comment by diegoefe** [comment]
Esto iría sólo en /organization/project, no?

**Comment by emilioplatzer** [comment]
Sí
