### ISSUE TITLE
crear el servicio GET /manual-push/organizacion/proyecto

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/qa-control-server#6]
Para poder probar a mano sin usar el push complejo. Si se necesitan parámetros pasarlos en la forma clásica `?variable=valor&variable2=valor2` 

Eso solo tiene que ocurrir si en la configuración dice production: false (si no debe fallar)

Así se saltea la parte de analizar y desencriptar el header

**Comment by emilioplatzer** [comment]
Igual que con el push tradicional si el proyecto o la organización no existen deben fallar

**Comment by emilioplatzer** [comment]
Avancé bastante. Falta un if en la app para que el servicio solo esté colgado si está en modo desarrollo.

**Comment by diegoefe** [comment]
Funciona bien. Lo cerramos
