### ISSUE TITLE
servicio agregar proyecto

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/qa-control-server#8]
- POST /add/:organizacion/:proyecto
- GET /manual-add/:organizacion/:proyecto (solo si está en production: false)

agrega el proyecto dentro de la organización (o informa error si ya existía o si la organización no existe). 

El GET funciona sin necesidad de loguearse

**Comment by diegoefe** [comment]
El proyecto ya debe existir en params/projects.json o este comando lo agrega también ahí?

**Comment by emilioplatzer** [comment]
Agregar proyecto supone que no existe, tiene que agregarlo en todos los
lugares donde se necesite después.

Este tiene que ser el único lugar donde se agregue el proyecto.
